### ISSUE TITLE
RE: fatal error: file_disvar.h: No such file or directory

### ISSUE THREAD

**Issue by mrgw454** [mburkley/ti994a#27]
Hello,

Trying this out for the first time (Debian 12 Bookworm) and getting the following error after pulling source from git:

```
file_disvar.c:30:10: fatal error: file_disvar.h: No such file or directory
   30 | #include "file_disvar.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
	[CC] ti994a.c...
make: *** [Makefile:60: file_disvar.o] Error 1

```

Not sure where the missing file is located.  Is there a specific library I'm missing?

Thanks for any help you can provide!

**Comment by mburkley** [comment]
Oops, I missed a file.  Apologies - it's committed now

**Comment by mrgw454** [comment]
All set -- thank you for your quick response!
